(* TODO
* Support n-ary expressions
* make function names consistent with smt-lib
* nt[i] notation
* Don't use separate AST constructor for each built-in function; instead, use 
  BinaryFunc, NaryFunc, etc. parameterized by func_name 
  *)

type unary_operator = 
| UPlus 
| UMinus
| LNot
| BVNot

type comp_operator = 
| Lt 
| Lte 
| Gt 
| Gte 
| Eq
| BVLt 
| BVLte
| BVGt 
| BVGte
| StrPrefix
| StrContains

type bin_operator = 
| BVAnd 
| BVOr 
| BVXor 
| LAnd
(* Generated logical and, to distinguish from user input logical and *)
| GLAnd
| LOr
| LXor 
| LImplies 
| Plus 
| Minus 
| Times 
| Div
| Mod
| StrConcat
| SetUnion
| SetIntersection
| SetMembership 

type il_type = 
| Unit
| Bool 
| Int 
| Placeholder
| String
| BitVector of int 
| BitList
| ADT of string list list
| Set of il_type

type builtin_func = 
| Repeat
| ReUnion
| ReRange
| StrInRe 
| StrToRe 
| ReStar 
| ReConcat 
| Length 
| StrLength 
| SeqLength 
| UbvToInt 
| SbvToInt 

type expr = 
| InhAttr of string * Lexing.position 
| SynthAttr of string * string * Lexing.position (* NT string * attribute name *)
| EmptySet of il_type * Lexing.position
| Singleton of expr * Lexing.position
| BinOp of expr * bin_operator * expr * Lexing.position
| UnOp of unary_operator * expr * Lexing.position
| CompOp of expr * comp_operator * expr * Lexing.position
| BVCast of int * expr * Lexing.position
(* The int options are initially None, but may be populated by the tool as a  
   structured form of renaming to clarify ambiguous dot notation references.
   *)
| NTExpr of (string * int option * int option) list * Lexing.position
| BVConst of int * bool list * Lexing.position
| BLConst of bool list * Lexing.position
| BConst of bool * Lexing.position
| IntConst of int * Lexing.position
| PhConst of string * Lexing.position
| StrConst of string * Lexing.position
| BuiltInFunc of builtin_func * expr list * Lexing.position
(* Not in user-facing syntax. Generated by Goblin to handle constraint applicability. *)
| ActLit of expr * Lexing.position

type semantic_constraint = 
| DerivedField of string * expr * Lexing.position (* <nonterminal> <- <expression> *)
| SmtConstraint of expr * Lexing.position (* Any boolean expression *)
| AttrDef of string * expr * Lexing.position (* attribute := <expression> *)

type grammar_element = 
(* Nonterminal name * optional RHS index * optional NT index * 
   inherited attributes * position *)
| Nonterminal of string * int option * int option * expr list * Lexing.position
| StubbedNonterminal of string * string (* Ignore *)

type prod_rule_rhs =
(* float denotes production rule option probability *)
| Rhs of grammar_element list * semantic_constraint list * float option * Lexing.position
| StubbedRhs of string (* Ignore *)

type element = 
(* NT LHS * inherited attributes * RHSs * position *)
| ProdRule of string * string list * prod_rule_rhs list * Lexing.position
| TypeAnnotation of string * il_type * semantic_constraint list * Lexing.position

(* This is the type of the grammar terms *)
type ast = element list

(* This function is used before desugaring dot expressions *)
(* TODO: Why is this function returning a string list rather than a string list list? *)
let rec get_nts_from_expr: expr -> string list 
= fun expr -> 
  let r = get_nts_from_expr in
  match expr with 
  | NTExpr (nts, _) -> List.map (fun (a, _, _) -> a) nts 
  | SynthAttr (nt, _, _) -> [nt] 
  | BinOp (expr1, _, expr2, _) -> 
    r expr1 @ r expr2
  | BVCast (_, expr, _) 
  | ActLit (expr, _)
  | UnOp (_, expr, _) -> 
    r expr
  | CompOp (expr1, _, expr2, _) -> 
    r expr1 @ r expr2
  | Singleton (expr, _) -> r expr
  | BuiltInFunc (_, exprs, _) -> 
    List.concat_map r exprs
  | BVConst _ 
  | BLConst _ 
  | BConst _ 
  | PhConst _
  | IntConst _ 
  | StrConst _
  | InhAttr _
  | EmptySet _  -> [] 

let rec get_nts_from_expr2: expr -> (string * int option * int option) list list
= fun expr -> 
  let r = get_nts_from_expr2 in
  match expr with 
  | NTExpr (nts, _) -> [nts]
  | InhAttr _
  | SynthAttr _ -> assert false
  | BinOp (expr1, _, expr2, _) -> 
    r expr1 @ r expr2
  | ActLit (expr, _)
  | UnOp (_, expr, _) -> 
    r expr
  | CompOp (expr1, _, expr2, _) -> 
    r expr1 @ r expr2
  | Singleton (expr, _) -> r expr
  | BuiltInFunc (_, exprs, _) -> 
    List.concat_map r exprs
  | BVCast (_, expr, _) ->
    r expr
  | BVConst _ 
  | BLConst _ 
  | BConst _ 
  | PhConst _
  | IntConst _ 
  | StrConst _ 
  | EmptySet _ -> []

let pp_print_nt_helper_dots: Format.formatter -> string * int option * int option -> unit 
= fun ppf (nt, idx1, idx2) -> 
  Format.fprintf ppf "<%s%s>" 
    nt
    (match idx1, idx2 with 
    | None, None -> ""
    | Some i, None -> "!" ^ string_of_int i ^ "!"
    | None, Some i -> "!" ^ string_of_int i
    | Some i, Some j -> "!" ^ string_of_int i ^ "!" ^ string_of_int j)

let pp_print_nt_helper_underscores: 
  Format.formatter -> string * int option * int option -> unit 
= fun ppf (nt, idx1, idx2) -> 
  Format.fprintf ppf "%s%s" 
    nt
    (match idx1, idx2 with 
    | None, None -> ""
    | Some i, None -> "!" ^ string_of_int i ^ "!"
    | None, Some i -> "!" ^ string_of_int i
    | Some i, Some j -> "!" ^ string_of_int i ^ "!" ^ string_of_int j)

let pp_print_nt_with_dots: Format.formatter -> (string * int option * int option) list -> unit
= fun ppf nt_expr -> 
  Format.fprintf ppf "%a"
  (Lib.pp_print_list pp_print_nt_helper_dots ".") nt_expr 

let pp_print_nt_with_underscores: 
  Format.formatter -> (string * int option * int option) list -> unit
= fun ppf nt_expr -> 
  Format.fprintf ppf "<%a>"
  (Lib.pp_print_list pp_print_nt_helper_underscores "_") nt_expr 

let pp_print_bin_op: Format.formatter -> bin_operator -> unit
= fun ppf op -> match op with 
| BVAnd -> Format.fprintf ppf "bvand"
| BVOr -> Format.fprintf ppf "bvor"
| BVXor -> Format.fprintf ppf "bvxor"
| GLAnd 
| LAnd -> Format.fprintf ppf "and"
| LOr -> Format.fprintf ppf "or"
| LXor -> Format.fprintf ppf "xor"
| LImplies -> Format.fprintf ppf "=>"
| Plus -> Format.fprintf ppf "+"
| Minus -> Format.fprintf ppf "-"
| Times -> Format.fprintf ppf "*"
| Div -> Format.fprintf ppf "div"
| Mod -> Format.fprintf ppf "mod"
| StrConcat -> Format.fprintf ppf "str.++"
| SetMembership | SetUnion | SetIntersection -> 
  Utils.crash "Unexpected case in pp_print_bin_op"

let pp_print_unary_op: Format.formatter -> unary_operator -> unit 
= fun ppf op -> match op with 
| UPlus -> Format.fprintf ppf  "+"
| UMinus -> Format.fprintf ppf  "-"
| LNot -> Format.fprintf ppf  "not"
| BVNot -> Format.fprintf ppf  "bvnot"

let pp_print_comp_op: Format.formatter -> comp_operator -> unit 
= fun ppf op -> match op with 
| Lt -> Format.fprintf ppf "<"
| Lte -> Format.fprintf ppf "<="
| Gt  -> Format.fprintf ppf ">"
| Gte -> Format.fprintf ppf ">="
| Eq -> Format.fprintf ppf "="
| BVLt -> Format.fprintf ppf  "bvult"
| BVLte -> Format.fprintf ppf  "bvulte"
| BVGt -> Format.fprintf ppf  "bvugt"
| BVGte -> Format.fprintf ppf  "bvugte"
| StrPrefix -> Format.fprintf ppf "str.prefixof"
| StrContains -> Format.fprintf ppf "str.contains"

let rec pp_print_ty: Format.formatter -> il_type -> unit 
= fun ppf ty -> match ty with 
| Unit -> Format.printf "Unit"
| Bool -> Format.fprintf ppf "Bool"
| Int -> Format.fprintf ppf "Int"
| Placeholder -> Format.fprintf ppf "Placeholder"
| String -> Format.fprintf ppf "String"
| BitList -> Format.fprintf ppf "List(Bool)" 
| BitVector width -> Format.fprintf ppf "BitVec(%d)" width
| Set ty -> Format.fprintf ppf "Set(%a)" pp_print_ty ty
| ADT rules -> 
  Format.fprintf ppf "ADT: %a"
    (Lib.pp_print_list (Lib.pp_print_list Format.pp_print_string " ") "; ") rules

let pp_print_builtin_func ppf func = 
  match func with 
  | StrLength -> Format.fprintf ppf "str.len"
  | Repeat -> Format.fprintf ppf "repeat"
  | ReUnion -> Format.fprintf ppf "re.union"
  | ReRange -> Format.fprintf ppf "re.range"
  | StrInRe -> Format.fprintf ppf "str.in_re"
  | StrToRe -> Format.fprintf ppf "str.to_re"
  | ReStar -> Format.fprintf ppf "re.*"
  | ReConcat -> Format.fprintf ppf "re.concat"
  | Length -> Format.fprintf ppf "length"
  | SeqLength -> Format.fprintf ppf "seq.len"
  | UbvToInt -> Format.fprintf ppf "ubv_to_int"
  | SbvToInt -> Format.fprintf ppf "sbv_to_int"

let rec pp_print_expr: Format.formatter -> expr -> unit 
= fun ppf expr -> match expr with
| SynthAttr (nt, attr, _) -> 
  Format.fprintf ppf "<%s>.%s"
    nt attr
| InhAttr (attr, _) -> Format.pp_print_string ppf attr
| EmptySet (ty, _) -> 
  Format.fprintf ppf "set.empty<%a>"
    pp_print_ty ty
| Singleton (expr, _) -> 
  Format.fprintf ppf "set.singleton(%a)" 
    pp_print_expr expr
| BinOp (expr1, SetMembership, expr2, _) -> 
  Format.fprintf ppf "set.member(%a, %a)"
    pp_print_expr expr1
    pp_print_expr expr2
| BinOp (expr1, SetUnion, expr2, _) -> 
  Format.fprintf ppf "set.union(%a, %a)"
    pp_print_expr expr1
    pp_print_expr expr2
| BinOp (expr1, SetIntersection, expr2, _) -> 
  Format.fprintf ppf "set.intersect(%a, %a)"
    pp_print_expr expr1
    pp_print_expr expr2
| BinOp (expr1, op, expr2, _) -> 
  Format.fprintf ppf "(%a %a %a)" 
    pp_print_expr expr1 
    pp_print_bin_op op 
    pp_print_expr expr2
| UnOp (op, expr, _) -> 
  Format.fprintf ppf "(%a %a)" 
    pp_print_unary_op op 
    pp_print_expr expr
| CompOp (expr1, op, expr2, _) -> 
  Format.fprintf ppf "(%a %a %a)" 
    pp_print_expr expr1 
    pp_print_comp_op op 
    pp_print_expr expr2
| BuiltInFunc (func, exprs, _) -> 
  Format.fprintf ppf "%a(%a)"
    pp_print_builtin_func func
    (Lib.pp_print_list pp_print_expr ", ") exprs
| BVCast (width, expr, _) -> 
  Format.fprintf ppf "int_to_bv(%d, %a)" 
    width 
    pp_print_expr expr 
| ActLit (expr, _) ->
  Format.fprintf ppf "ActLit(%a)"
    pp_print_expr expr
| NTExpr ([nt_expr], _) -> 
  if !Flags.dump_clp then 
    let s = nt_expr |> Utils.tr_fst |> String.uppercase_ascii in
    Format.pp_print_string ppf s
  else pp_print_nt_with_underscores ppf ([nt_expr]) 
| NTExpr (nt_expr, _) -> 
  if !Flags.dump_clp then 
    let s = Utils.last nt_expr |> Utils.tr_fst |> (fun x -> x ^ "s") |> String.uppercase_ascii in
    let init = Utils.init nt_expr |> List.map Utils.tr_fst |> String.concat "_" in
    Format.pp_print_string ppf (init ^ "_" ^ s)
  else pp_print_nt_with_dots ppf (nt_expr) 
| BLConst (bits, _) -> 
  let bits = List.map Bool.to_int bits in
  Format.fprintf ppf "(BitList 0b%a)"
    (Lib.pp_print_list Format.pp_print_int "") bits
| BVConst (_, bits, _) -> 
  let bits = List.map Bool.to_int bits in
  Format.fprintf ppf "0b%a"
    (Lib.pp_print_list Format.pp_print_int "") bits
| BConst (b, _) -> Format.fprintf ppf "%b" b
| IntConst (i, _) -> Format.fprintf ppf "%d" i
| PhConst (s, _) -> Format.fprintf ppf "\"%s\"" s
| StrConst (s, _) -> Format.fprintf ppf "\"%s\"" s

let pp_print_semantic_constraint: Format.formatter -> semantic_constraint -> unit 
= fun ppf sc -> match sc with 
| DerivedField (nt, expr, _) -> 
  Format.fprintf ppf "<%a> <- %a;"
    Format.pp_print_string nt 
    pp_print_expr expr
| SmtConstraint (expr, _) -> 
  Format.fprintf ppf "%a;"
    pp_print_expr expr
| AttrDef (attr, expr, _) -> 
  Format.fprintf ppf "%s := %a;"
    attr 
    pp_print_expr expr

let pp_print_grammar_element: Format.formatter -> grammar_element ->  unit 
= fun ppf g_el -> match g_el with 
| Nonterminal (nt, idx1, idx2, ias, _) -> (
  match ias with 
  | [] -> pp_print_nt_with_dots ppf [nt, idx1, idx2]
  | _ :: _ -> 
    Format.fprintf ppf "%a(%a)"
      pp_print_nt_with_dots [nt, idx1, idx2] 
      (Lib.pp_print_list pp_print_expr ", ") ias
  )
| StubbedNonterminal (_, stub_id) -> Format.pp_print_string ppf stub_id

let pp_print_prob ppf prob = 
  match prob with
  | None -> () 
  | Some prob -> Format.fprintf ppf " %f" prob 

let pp_print_prod_rule_rhs: Format.formatter -> prod_rule_rhs -> unit 
= fun ppf rhss -> 
  match rhss with 
| Rhs (ges, [], prob, _) -> 
  Format.fprintf ppf "%a%a"
  (Lib.pp_print_list pp_print_grammar_element " ") ges
  pp_print_prob prob
| Rhs (ges, scs, prob, _) ->
  Format.fprintf ppf "%a \n{ %a }%a"
  (Lib.pp_print_list pp_print_grammar_element " ") ges
  (Lib.pp_print_list pp_print_semantic_constraint " ") scs
  pp_print_prob prob
| StubbedRhs stub_id -> 
  Format.pp_print_string ppf stub_id

let pp_print_element: Format.formatter -> element ->  unit 
= fun ppf el -> match el with 
| ProdRule (nt, [], rhss, _) -> 
  Format.fprintf ppf "%a ::= %a;"
    pp_print_nt_with_dots [nt, None, None]
    (Lib.pp_print_list pp_print_prod_rule_rhs " | ") rhss

| ProdRule (nt, ias, rhss, _) -> 
  Format.fprintf ppf "%a(%a) ::= %a;"
    pp_print_nt_with_dots [nt, None, None]
    (Lib.pp_print_list Format.pp_print_string ", ") ias
    (Lib.pp_print_list pp_print_prod_rule_rhs " | ") rhss

| TypeAnnotation (nt, ty, [], _) -> 
  Format.fprintf ppf "%a :: %a;"
    pp_print_nt_with_dots [nt, None, None] 
    pp_print_ty ty

| TypeAnnotation (nt, ty, scs, _) -> 
  Format.fprintf ppf "%a :: %a { %a };"
    pp_print_nt_with_dots [nt, None, None] 
    pp_print_ty ty
    (Lib.pp_print_list pp_print_semantic_constraint " ") scs

let pp_print_ast: Format.formatter -> ast ->  unit 
= fun ppf ast -> 
  Format.fprintf ppf "%a\n"
    (Lib.pp_print_list pp_print_element "\n") ast

let il_int_to_bv: int -> int -> Lexing.position -> expr 
= fun length n pos ->
  if n >= (1 lsl length) then
    (* NOTE: If we overflow, return max value *)
    BVConst (length, Utils.replicate true length, pos)
  else
    let rec to_bits acc len n =
      if len = 0 then acc
      else
        let bit = (n land 1) = 1 in
        to_bits (bit :: acc) (len - 1) (n lsr 1)
    in
    let bits = to_bits [] length n in 
    BVConst (length, bits, pos)

let grammar_element_to_string: grammar_element -> string 
= fun grammar_element -> match grammar_element with 
  | Nonterminal (nt2, _, _, _, _) -> nt2
  | StubbedNonterminal (_, stub_id) -> stub_id

(* Used before divide and conquer *)
let nts_of_rhs: prod_rule_rhs -> string list 
= fun rhs -> match rhs with 
| Rhs (ges, _, _, _) -> 
  List.map (fun ge -> match ge with 
  | Nonterminal (nt, _, _, _, _) -> nt 
  | StubbedNonterminal (nt, _) -> nt (* TODO: Not sure which tuple element we want, first or second *)
  ) ges
| StubbedRhs _ -> [] 

let rec expr_contains_dangling_nt: Utils.SILSet.t -> expr -> bool 
= fun ctx expr -> 
  let r = expr_contains_dangling_nt ctx in
  match expr with 
  | NTExpr (nt_expr, _) -> 
    let res = (List.length nt_expr > 1) && 
    not (Utils.SILSet.mem nt_expr ctx) in 
    (* Format.fprintf Format.std_formatter "Set {%a}: Is %a a member?: %b\n"
      (Lib.pp_print_list pp_print_nt_with_underscores ", ") (Utils.SILSet.elements ctx)
      pp_print_nt_with_underscores nt_expr (Utils.SILSet.mem nt_expr ctx); *)
    res
  | SynthAttr (nt, _, p) -> 
    r (NTExpr ([nt, None, None], p))
  | BinOp (expr1, _, expr2, _) -> 
    r expr1 || r expr2
  | ActLit (expr, _)
  | UnOp (_, expr, _) -> 
    r expr
  | CompOp (expr1, _, expr2, _) -> 
    r expr1 || r expr2
  | Singleton (expr, _) -> r expr
  | BuiltInFunc (_, exprs, _) -> List.map r exprs |> List.fold_left (||) false  
  | BVCast (_, expr, _)  -> r expr
  | BVConst _ 
  | BLConst _ 
  | BConst _ 
  | PhConst _
  | IntConst _ 
  | StrConst _ 
  | InhAttr _
  | EmptySet _ -> false

let sc_constrains_nt: string -> semantic_constraint -> bool 
= fun nt sc -> match sc with 
| SmtConstraint (expr, _) -> List.mem nt (get_nts_from_expr expr)
| DerivedField (nt2, _, _) 
| AttrDef (nt2, _, _) -> nt = nt2

let get_nts_from_sc: semantic_constraint -> string list 
= fun sc -> match sc with 
| SmtConstraint (expr, _) -> get_nts_from_expr expr
| AttrDef (nt2, _, _)
| DerivedField (nt2, _, _) -> [nt2]

(* To be called before desugaring NTs to match expressions and resolving ambiguities.
   This may seem overconservative, but in the sygus_dac approach, we have to have subproblems 
   be completely independent to stub them out. E.g., consider 
   <A> -> <B> { <B>.<C> < 5 };
   <B> -> <C> <D> { <D> < 6 }; 
   It may seem these should not overlap. But in the sygus approach, they must, 
   because otherwise we will try to stub out <B>, but then <B>.<C> will fail.
   *)
let ast_constrains_nt: ast -> string -> bool 
= fun ast nt -> 
  List.exists (fun element -> match element with 
    | TypeAnnotation (nt2, _, _ :: _, _) when nt = nt2 -> true 
    | TypeAnnotation _ -> false
    | ProdRule (_, _, rhss, _) -> List.exists (fun rhs -> match rhs with 
      | Rhs (_, scs, _, _) -> List.exists (sc_constrains_nt nt) scs
      | StubbedRhs _ -> false
    ) rhss
  ) ast

(* Use before resolving constraint ambiguities *)
let rec prepend_nt_to_dot_exprs: string -> expr -> expr 
= fun nt expr -> 
  let r = prepend_nt_to_dot_exprs nt in
  match expr with
  | NTExpr (nts, pos) -> NTExpr ((nt, None, None) :: nts, pos)
  | BVCast (len, expr, pos) -> BVCast (len, r expr, pos)
  | BinOp (expr1, op, expr2, pos) -> BinOp (r expr1, op, r expr2, pos) 
  | UnOp (op, expr, pos) -> UnOp (op, r expr, pos) 
  | CompOp (expr1, op, expr2, pos) -> CompOp (r expr1, op, r expr2, pos) 
  | Singleton (expr, pos) -> Singleton (r expr, pos)
  | BuiltInFunc (func, exprs, pos) -> BuiltInFunc (func, List.map r exprs, pos) 
  | BVConst _ 
  | BLConst _ 
  | BConst _ 
  | IntConst _ 
  | PhConst _ 
  | StrConst _
  | EmptySet _ -> expr
  | InhAttr _
  | SynthAttr _ -> assert false
  | ActLit _ -> assert false

let scs_of_element = function 
| ProdRule (_, _, rhss, _) -> 
  List.concat_map (function 
  | StubbedRhs _ -> [] 
  | Rhs (_, scs, _, _) -> scs
  ) rhss
| TypeAnnotation (_, _, scs, _) -> scs

let rec nts_of_ast ast = match ast with 
| [] -> Utils.StringSet.empty  
| ProdRule (nt, _, rhss, _) :: tl -> 
  let nts = nt :: (List.concat_map nts_of_rhs rhss) in 
  let nts = Utils.StringSet.of_list nts in 
  Utils.StringSet.union nts (nts_of_ast tl)
| TypeAnnotation (nt, _, _, _) :: tl -> 
  let nts = Utils.StringSet.singleton nt in 
  Utils.StringSet.union nts (nts_of_ast tl)

let find_element ast nt = 
  List.find (fun element -> match element with 
  | TypeAnnotation (nt', _, _, _) 
  | ProdRule (nt', _, _, _) -> String.equal nt nt'
  ) ast 

let pos_of_expr expr = match expr with 
| NTExpr (_, pos) 
| BVCast (_, _, pos) 
| BinOp (_, _, _, pos) 
| UnOp (_, _, pos) 
| CompOp (_, _, _, pos) 
| Singleton (_, pos) 
| BuiltInFunc (_, _, pos) 
| BVConst (_, _, pos) 
| BLConst (_, pos)
| BConst (_, pos) 
| IntConst (_, pos) 
| PhConst (_, pos) 
| StrConst (_, pos) 
| SynthAttr (_, _, pos)
| InhAttr (_, pos)
| ActLit (_, pos) 
| EmptySet (_, pos) -> pos 

let rec eq_il_type ty1 ty2 = match ty1, ty2 with 
| Unit, Unit
| Bool, Bool
| Int, Int
| (Placeholder | String), (Placeholder | String)
| BitList, BitList -> true
| BitVector w1, BitVector w2 -> w1 = w2
| ADT s1, ADT s2 -> 
  List.length s1 = List.length s1 &&
  List.for_all2 (fun s1 s2 -> 
    List.length s1 = List.length s2 && 
    List.for_all2 String.equal s1 s2
  ) s1 s2
| Set ty1, Set ty2 -> eq_il_type ty1 ty2
| _ -> false

let ges_of_rhs rhs = match rhs with 
| StubbedRhs _ -> assert false 
| Rhs (ges, _, _, _) -> ges
